/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diaketas.UI.Movil;

import diaketas.Modelo.ONG.Donante;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author klyone
 * 
 * Formulario principal con los datos del donante y permite a este modificarlos.
 * 
 */
public class jFormularioModificar extends javax.swing.JPanel {

    jSTeclado tv = null;
    Donante donante = null;
    /**
     * Creates new form jFormularioModificar
     */
    public jFormularioModificar() {
        initComponents();
        
        String dia;
        String mes;
        String anio;
        String fnac;
        
        tv = new jSTeclado(localidad_input3);
        
        donante = diaketas.diaketas.ong.gestorDonantes.obtenerDatosDonante();
        
        fnac = donante.obtenerFechaNac().toString();
        
        anio = fnac.substring(0,4);
        mes = fnac.substring(5,7);
        dia = fnac.substring(8,10);
        
        int anio_ent = Integer.parseInt(anio);
        int mes_ent = Integer.parseInt(mes);
        int dia_ent = Integer.parseInt(dia);
        
        anio_ent -= 1900;
        mes_ent -= 1;
        dia_ent -= 1;
        
        dni_input3.setText(donante.obtenerNIFCIF());
        nombre_input3.setText(donante.obtenerNombre());
        apellidos_input3.setText(donante.obtenerApellidos());
        tipo_donante_input3.setText(donante.obtenerTipoDonante());
        dia_input3.setSelectedIndex(dia_ent);
        mes_input3.setSelectedIndex(mes_ent);
        anio_input3.setSelectedIndex(anio_ent);
        localidad_input3.setText(donante.obtenerLocalidad());
        telefono_input3.setText(String.valueOf(donante.obtenerTelefono()));
        email_input3.setText(donante.obtenerEmail());
        fecha_inscripcion_input3.setText(donante.obtenerFechaInscripcion().toString());
        observaciones_input3.setText(donante.obtenerObservaciones());
        tipo_periodicidad_input3.setSelectedItem(donante.obtenerTipoPeriodicidad());
        periodicidad_donaciones_input3.setText(String.valueOf(donante.obtenerPeriodicidadDonaciones()));
        cuantia_input3.setText(String.valueOf(donante.obtenerCuantiaDonaciones()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dni_etiq3 = new javax.swing.JLabel();
        dni_input3 = new javax.swing.JTextField();
        nombre_etiq3 = new javax.swing.JLabel();
        nombre_input3 = new javax.swing.JTextField();
        apellidos_etiq3 = new javax.swing.JLabel();
        apellidos_input3 = new javax.swing.JTextField();
        tipo_donante_etiq3 = new javax.swing.JLabel();
        tipo_donante_input3 = new javax.swing.JTextField();
        fecha_nacimiento_etiq3 = new javax.swing.JLabel();
        dia_input3 = new javax.swing.JComboBox();
        mes_input3 = new javax.swing.JComboBox();
        anio_input3 = new javax.swing.JComboBox();
        localidad_etiq3 = new javax.swing.JLabel();
        localidad_input3 = new javax.swing.JTextField();
        telefono_etiq3 = new javax.swing.JLabel();
        telefono_input3 = new javax.swing.JTextField();
        email_etiq3 = new javax.swing.JLabel();
        email_input3 = new javax.swing.JTextField();
        fecha_inscripcion_etiq3 = new javax.swing.JLabel();
        fecha_inscripcion_input3 = new javax.swing.JTextField();
        observaciones_etiq3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        observaciones_input3 = new javax.swing.JTextArea();
        tipo_periodicidad_etiq3 = new javax.swing.JLabel();
        tipo_periodicidad_input3 = new javax.swing.JComboBox();
        periodicidad_donaciones_etiq3 = new javax.swing.JLabel();
        periodicidad_donaciones_input3 = new javax.swing.JTextField();
        cuantia_etiq3 = new javax.swing.JLabel();
        cuantia_input3 = new javax.swing.JTextField();
        bmodificarFecha = new javax.swing.JToggleButton();
        bmodificartperiodicidad = new javax.swing.JToggleButton();

        setMaximumSize(null);

        dni_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dni_etiq3.setText("DNI:");

        dni_input3.setBackground(new java.awt.Color(255, 204, 204));
        dni_input3.setEditable(false);
        dni_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dni_input3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dni_input3.setMaximumSize(new java.awt.Dimension(220, 50));
        dni_input3.setMinimumSize(new java.awt.Dimension(50, 30));
        dni_input3.setPreferredSize(null);
        dni_input3.setVerifyInputWhenFocusTarget(false);

        nombre_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre_etiq3.setText("Nombre:");

        nombre_input3.setBackground(new java.awt.Color(255, 204, 204));
        nombre_input3.setEditable(false);
        nombre_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre_input3.setMaximumSize(null);

        apellidos_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apellidos_etiq3.setText("Apellidos:");

        apellidos_input3.setBackground(new java.awt.Color(255, 204, 204));
        apellidos_input3.setEditable(false);
        apellidos_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tipo_donante_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipo_donante_etiq3.setText("Tipo donante:");

        tipo_donante_input3.setBackground(new java.awt.Color(255, 204, 204));
        tipo_donante_input3.setEditable(false);
        tipo_donante_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        fecha_nacimiento_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fecha_nacimiento_etiq3.setText("Fecha nacimiento:");

        dia_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dia_input3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mes_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mes_input3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        anio_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        anio_input3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099", "2100", "2101", "2102", "2103", "2104", "2105", "2106", "2107", "2108", "2109", "2110", "2111", "2112", "2113", "2114", "2115", "2116", "2117", "2118", "2119", "2120", "2121", "2122", "2123", "2124", "2125", "2126", "2127", "2128", "2129", "2130", "2131", "2132", "2133", "2134", "2135", "2136", "2137", "2138", "2139", "2140", "2141", "2142", "2143", "2144", "2145", "2146", "2147", "2148", "2149", "2150", "2151", "2152", "2153", "2154", "2155", "2156", "2157", "2158", "2159", "2160", "2161", "2162", "2163", "2164", "2165", "2166", "2167", "2168", "2169", "2170", "2171", "2172", "2173", "2174", "2175", "2176", "2177", "2178", "2179", "2180", "2181", "2182", "2183", "2184", "2185", "2186", "2187", "2188", "2189", "2190", "2191", "2192", "2193", "2194", "2195", "2196", "2197", "2198", "2199", "2200", "2201", "2202", "2203", "2204", "2205", "2206", "2207", "2208", "2209", "2210", "2211", "2212", "2213", "2214", "2215", "2216", "2217", "2218", "2219", "2220", "2221", "2222", "2223", "2224", "2225", "2226", "2227", "2228", "2229", "2230", "2231", "2232", "2233", "2234", "2235", "2236", "2237", "2238", "2239", "2240", "2241", "2242", "2243", "2244", "2245", "2246", "2247", "2248", "2249", "2250", "2251", "2252", "2253", "2254", "2255", "2256", "2257", "2258", "2259", "2260", "2261", "2262", "2263", "2264", "2265", "2266", "2267", "2268", "2269", "2270", "2271", "2272", "2273", "2274", "2275", "2276", "2277", "2278", "2279", "2280", "2281", "2282", "2283", "2284", "2285", "2286", "2287", "2288", "2289", "2290", "2291", "2292", "2293", "2294", "2295", "2296", "2297", "2298", "2299", "2300", "2301", "2302", "2303", "2304", "2305", "2306", "2307", "2308", "2309", "2310", "2311", "2312", "2313", "2314", "2315", "2316", "2317", "2318", "2319", "2320", "2321", "2322", "2323", "2324", "2325", "2326", "2327", "2328", "2329", "2330", "2331", "2332", "2333", "2334", "2335", "2336", "2337", "2338", "2339", "2340", "2341", "2342", "2343", "2344", "2345", "2346", "2347", "2348", "2349", "2350", "2351", "2352", "2353", "2354", "2355", "2356", "2357", "2358", "2359", "2360", "2361", "2362", "2363", "2364", "2365", "2366", "2367", "2368", "2369", "2370", "2371", "2372", "2373", "2374", "2375", "2376", "2377", "2378", "2379", "2380", "2381", "2382", "2383", "2384", "2385", "2386", "2387", "2388", "2389", "2390", "2391", "2392", "2393", "2394", "2395", "2396", "2397", "2398", "2399", "2400" }));

        localidad_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        localidad_etiq3.setText("Localidad:");

        localidad_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        localidad_input3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                localidad_input3localidad_inputMouseClicked(evt);
            }
        });
        localidad_input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidad_input3ActionPerformed(evt);
            }
        });

        telefono_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefono_etiq3.setText("Telefono:");

        telefono_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefono_input3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefono_input3telefono_inputMouseClicked(evt);
            }
        });
        telefono_input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono_input3ActionPerformed(evt);
            }
        });

        email_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_etiq3.setText("Email:");

        email_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_input3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                email_input3email_inputMouseClicked(evt);
            }
        });
        email_input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_input3ActionPerformed(evt);
            }
        });

        fecha_inscripcion_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fecha_inscripcion_etiq3.setText("Fecha inscripción:");

        fecha_inscripcion_input3.setBackground(new java.awt.Color(255, 204, 204));
        fecha_inscripcion_input3.setEditable(false);
        fecha_inscripcion_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        observaciones_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        observaciones_etiq3.setText("Observaciones:");

        observaciones_input3.setBackground(new java.awt.Color(255, 204, 204));
        observaciones_input3.setColumns(20);
        observaciones_input3.setEditable(false);
        observaciones_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        observaciones_input3.setRows(5);
        jScrollPane7.setViewportView(observaciones_input3);

        tipo_periodicidad_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipo_periodicidad_etiq3.setText("Tipo periodicidad:");

        tipo_periodicidad_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipo_periodicidad_input3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguna", "Días", "Meses", "Años" }));

        periodicidad_donaciones_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        periodicidad_donaciones_etiq3.setText("Periodicidad:");

        periodicidad_donaciones_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        periodicidad_donaciones_input3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                periodicidad_donaciones_input3periodicidad_donaciones_inputMouseClicked(evt);
            }
        });
        periodicidad_donaciones_input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodicidad_donaciones_input3ActionPerformed(evt);
            }
        });

        cuantia_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cuantia_etiq3.setText("Importe:");

        cuantia_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cuantia_input3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuantia_input3cuantia_inputMouseClicked(evt);
            }
        });
        cuantia_input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuantia_input3ActionPerformed(evt);
            }
        });

        bmodificarFecha.setBackground(new java.awt.Color(153, 153, 255));
        bmodificarFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bmodificarFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diaketas/Iconos/lazpiz_modificar_peke.png"))); // NOI18N
        bmodificarFecha.setText("Modificar");
        bmodificarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificarFechaActionPerformed(evt);
            }
        });

        bmodificartperiodicidad.setBackground(new java.awt.Color(153, 153, 255));
        bmodificartperiodicidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bmodificartperiodicidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diaketas/Iconos/lazpiz_modificar_peke.png"))); // NOI18N
        bmodificartperiodicidad.setText("Modificar");
        bmodificartperiodicidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificartperiodicidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tipo_periodicidad_etiq3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipo_periodicidad_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bmodificartperiodicidad)
                        .addGap(18, 18, 18)
                        .addComponent(periodicidad_donaciones_etiq3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(periodicidad_donaciones_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cuantia_etiq3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuantia_input3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fecha_nacimiento_etiq3)
                        .addGap(18, 18, 18)
                        .addComponent(dia_input3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)
                        .addComponent(mes_input3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(anio_input3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80)
                        .addComponent(bmodificarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(apellidos_etiq3)
                                .addGap(18, 18, 18)
                                .addComponent(apellidos_input3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dni_etiq3)
                                .addGap(18, 18, 18)
                                .addComponent(dni_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nombre_etiq3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipo_donante_etiq3)
                                .addGap(27, 27, 27)
                                .addComponent(tipo_donante_input3))
                            .addComponent(nombre_input3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(email_etiq3)
                                .addGap(18, 18, 18)
                                .addComponent(email_input3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(localidad_etiq3)
                                .addGap(18, 18, 18)
                                .addComponent(localidad_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(telefono_etiq3)
                                .addGap(18, 18, 18)
                                .addComponent(telefono_input3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fecha_inscripcion_etiq3)
                                .addGap(18, 18, 18)
                                .addComponent(fecha_inscripcion_input3))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(observaciones_etiq3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dni_etiq3)
                    .addComponent(nombre_etiq3)
                    .addComponent(nombre_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos_etiq3)
                    .addComponent(apellidos_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo_donante_etiq3)
                    .addComponent(tipo_donante_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha_nacimiento_etiq3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dia_input3)
                    .addComponent(mes_input3)
                    .addComponent(anio_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmodificarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localidad_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localidad_etiq3)
                    .addComponent(telefono_etiq3)
                    .addComponent(telefono_input3))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_etiq3)
                    .addComponent(email_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_inscripcion_etiq3)
                    .addComponent(fecha_inscripcion_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(observaciones_etiq3)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bmodificartperiodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo_periodicidad_etiq3)
                    .addComponent(periodicidad_donaciones_etiq3)
                    .addComponent(periodicidad_donaciones_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuantia_etiq3)
                    .addComponent(tipo_periodicidad_input3)
                    .addComponent(cuantia_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void localidad_input3localidad_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localidad_input3localidad_inputMouseClicked
        // TODO add your handling code here:
        tv.asociarCampo(localidad_input3);
        tv.activar();
    }//GEN-LAST:event_localidad_input3localidad_inputMouseClicked

    private void telefono_input3telefono_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefono_input3telefono_inputMouseClicked
        // TODO add your handling code here:
        tv.asociarCampo(telefono_input3);
        tv.activar();
    }//GEN-LAST:event_telefono_input3telefono_inputMouseClicked

    private void email_input3email_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_input3email_inputMouseClicked
        // TODO add your handling code here:
        
        tv.asociarCampo(email_input3);
        tv.activar();
    }//GEN-LAST:event_email_input3email_inputMouseClicked

    private void periodicidad_donaciones_input3periodicidad_donaciones_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_periodicidad_donaciones_input3periodicidad_donaciones_inputMouseClicked
        // TODO add your handling code here:
        
        tv.asociarCampo(periodicidad_donaciones_input3);
        tv.activar();
    }//GEN-LAST:event_periodicidad_donaciones_input3periodicidad_donaciones_inputMouseClicked

    private void cuantia_input3cuantia_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuantia_input3cuantia_inputMouseClicked
        // TODO add your handling code here:
        
        tv.asociarCampo(cuantia_input3);
        tv.activar();
    }//GEN-LAST:event_cuantia_input3cuantia_inputMouseClicked

    private void localidad_input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidad_input3ActionPerformed
        // TODO add your handling code here:
        Object localidad = localidad_input3.getText();
        
        if(((String) localidad).compareTo("") != 0)
            diaketas.diaketas.ong.gestorDonantes.modificarElemento(localidad, 1);
        else
            JOptionPane.showMessageDialog(this, "No se ha introducido una localidad", "Localidad", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_localidad_input3ActionPerformed

    private void telefono_input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono_input3ActionPerformed
        // TODO add your handling code here:
        Object telefono = new Integer(Integer.parseInt(telefono_input3.getText()));
        
        
        if(((Integer) telefono).toString().length() == 9)
            diaketas.diaketas.ong.gestorDonantes.modificarElemento(telefono,2);
        else
            JOptionPane.showMessageDialog(this, "El telefono introducido no es correcto", "Telefono", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_telefono_input3ActionPerformed

    private void email_input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_input3ActionPerformed
        // TODO add your handling code here:
        Object email = email_input3.getText();
        
        if(ValidarCampos.ValidarCampos.isEmail((String) email))
            diaketas.diaketas.ong.gestorDonantes.modificarElemento(email,3);
        else
            JOptionPane.showMessageDialog(this, "El email introducido no es correcto", "Email", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_email_input3ActionPerformed

    private void bmodificartperiodicidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificartperiodicidadActionPerformed
        // TODO add your handling code here:
        Object tperiodicidad = tipo_periodicidad_input3.getSelectedItem().toString();
        
        diaketas.diaketas.ong.gestorDonantes.modificarElemento(tperiodicidad,4);
    }//GEN-LAST:event_bmodificartperiodicidadActionPerformed

    private void periodicidad_donaciones_input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodicidad_donaciones_input3ActionPerformed
        // TODO add your handling code here:
        Object periodicidad = new Integer(Integer.parseInt(periodicidad_donaciones_input3.getText()));
        
        if(((Integer) periodicidad).intValue() > 0)
            diaketas.diaketas.ong.gestorDonantes.modificarElemento(periodicidad,5);
        else
            JOptionPane.showMessageDialog(this, "La periodicidad no se ha introducido correctamente. Debe ser mayor que 0.", "Periodicidad", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_periodicidad_donaciones_input3ActionPerformed

    private void cuantia_input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuantia_input3ActionPerformed
        // TODO add your handling code here:
        Object cuantia = new Double(Double.parseDouble(cuantia_input3.getText()));
        
        if(((Double) cuantia).doubleValue() > 0)
            diaketas.diaketas.ong.gestorDonantes.modificarElemento(cuantia,6);
        else
            JOptionPane.showMessageDialog(this, "La cuantia de las donaciones introducida no es correcta. Debe ser mayor que 0.", "Cuantia", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_cuantia_input3ActionPerformed

    private void bmodificarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificarFechaActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy");
        String fechan = new String("");
        String dian = (String) dia_input3.getSelectedItem();
        String mesn = (String) mes_input3.getSelectedItem();
        String anion = (String) anio_input3.getSelectedItem();
        int dia_ent = Integer.parseInt(dian);
        int mes_ent = Integer.parseInt(mesn);
        int anio_ent = Integer.parseInt(anion);
        boolean error_dia = false;
        boolean anio_bisiesto = false;
        Object fecha_nac;
        
        switch(mes_ent) {
            case 2:
                anio_bisiesto = esBisiesto(anio_ent);
                if(anio_bisiesto) {
                    if(dia_ent > 29) {
                        error_dia = true;
                    }
                }
                else {
                    if(dia_ent > 28) {
                        error_dia = true;
                    }
                }
            break;
            case 4:
            case 6:
            case 9:
            case 11:
                if(dia_ent > 30) {
                    error_dia = true;
                }
                
        }
        
        if(!error_dia) {
            try {
                fechan = fechan + dian+"/";
                fechan = fechan + mesn+"/";
                fechan = fechan + anion;
            
                fecha_nac = formateador.parse(fechan);
                diaketas.diaketas.ong.gestorDonantes.modificarElemento(fecha_nac, 0);
            } catch (Exception e) {
                System.out.println("Error: La fecha formada no es correcta");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "La fecha de nacimiento introducida no es correcta", "Fecha nacimiento", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_bmodificarFechaActionPerformed

    /**
     * Calcula si un año es bisiesto
     * @param anio Año que se quiere comprobar
     * @return Devuelve true si es bisiesto y false en caso contrario
     */
   private boolean esBisiesto(int anio) {
        int bisiesto1 = 1900;
        boolean b = false;
        int fin = 2400;
        
        while(bisiesto1 <= fin) {
            if(bisiesto1 == anio) {
                b = true;
                break;
            }
            bisiesto1 += 4;
        }
        
        return b;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox anio_input3;
    private javax.swing.JLabel apellidos_etiq3;
    private javax.swing.JTextField apellidos_input3;
    private javax.swing.JToggleButton bmodificarFecha;
    private javax.swing.JToggleButton bmodificartperiodicidad;
    private javax.swing.JLabel cuantia_etiq3;
    private javax.swing.JTextField cuantia_input3;
    private javax.swing.JComboBox dia_input3;
    private javax.swing.JLabel dni_etiq3;
    private javax.swing.JTextField dni_input3;
    private javax.swing.JLabel email_etiq3;
    private javax.swing.JTextField email_input3;
    private javax.swing.JLabel fecha_inscripcion_etiq3;
    private javax.swing.JTextField fecha_inscripcion_input3;
    private javax.swing.JLabel fecha_nacimiento_etiq3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel localidad_etiq3;
    private javax.swing.JTextField localidad_input3;
    private javax.swing.JComboBox mes_input3;
    private javax.swing.JLabel nombre_etiq3;
    private javax.swing.JTextField nombre_input3;
    private javax.swing.JLabel observaciones_etiq3;
    private javax.swing.JTextArea observaciones_input3;
    private javax.swing.JLabel periodicidad_donaciones_etiq3;
    private javax.swing.JTextField periodicidad_donaciones_input3;
    private javax.swing.JLabel telefono_etiq3;
    private javax.swing.JTextField telefono_input3;
    private javax.swing.JLabel tipo_donante_etiq3;
    private javax.swing.JTextField tipo_donante_input3;
    private javax.swing.JLabel tipo_periodicidad_etiq3;
    private javax.swing.JComboBox tipo_periodicidad_input3;
    // End of variables declaration//GEN-END:variables
}
