/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diaketas.UI.Movil;

import diaketas.Modelo.ONG.Donante;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author klyone
 * 
 * Formulario principal con los datos del donante y permite a este modificarlos.
 * 
 */
public class jFormularioModificar extends javax.swing.JPanel {

    jSTeclado tv = null;
    Donante donante = null;
    /**
     * Creates new form jFormularioModificar
     */
    public jFormularioModificar() {
        initComponents();
        
        tv = new jSTeclado(localidad_input3);
        
        donante = diaketas.diaketas.ong.gestorDonantes.obtenerDatosDonante();
        
        dni_input3.setText(donante.obtenerNIFCIF());
        nombre_input3.setText(donante.obtenerNombre());
        apellidos_input3.setText(donante.obtenerApellidos());
        tipo_donante_input3.setText(donante.obtenerTipoDonante());
        dia_input3.setSelectedItem(new Integer(donante.obtenerFechaNac().getDay()));
        mes_input3.setSelectedItem(new Integer(donante.obtenerFechaNac().getMonth()));
        anio_input3.setSelectedItem(new Integer(donante.obtenerFechaNac().getYear()));
        localidad_input3.setText(donante.obtenerLocalidad());
        telefono_input3.setText(String.valueOf(donante.obtenerTelefono()));
        email_input3.setText(donante.obtenerEmail());
        fecha_inscripcion_input3.setText(donante.obtenerFechaInscripcion().toString());
        observaciones_input3.setText(donante.obtenerObservaciones());
        tipo_periodicidad_input3.setSelectedItem(donante.obtenerTipoPeriodicidad());
        periodicidad_donaciones_input3.setText(String.valueOf(donante.obtenerPeriodicidadDonaciones()));
        cuantia_input3.setText(String.valueOf(donante.obtenerCuantiaDonaciones()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dni_etiq3 = new javax.swing.JLabel();
        dni_input3 = new javax.swing.JTextField();
        nombre_etiq3 = new javax.swing.JLabel();
        nombre_input3 = new javax.swing.JTextField();
        apellidos_etiq3 = new javax.swing.JLabel();
        apellidos_input3 = new javax.swing.JTextField();
        tipo_donante_etiq3 = new javax.swing.JLabel();
        tipo_donante_input3 = new javax.swing.JTextField();
        fecha_nacimiento_etiq3 = new javax.swing.JLabel();
        dia_input3 = new javax.swing.JComboBox();
        mes_input3 = new javax.swing.JComboBox();
        anio_input3 = new javax.swing.JComboBox();
        localidad_etiq3 = new javax.swing.JLabel();
        localidad_input3 = new javax.swing.JTextField();
        telefono_etiq3 = new javax.swing.JLabel();
        telefono_input3 = new javax.swing.JTextField();
        email_etiq3 = new javax.swing.JLabel();
        email_input3 = new javax.swing.JTextField();
        fecha_inscripcion_etiq3 = new javax.swing.JLabel();
        fecha_inscripcion_input3 = new javax.swing.JTextField();
        observaciones_etiq3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        observaciones_input3 = new javax.swing.JTextArea();
        tipo_periodicidad_etiq3 = new javax.swing.JLabel();
        tipo_periodicidad_input3 = new javax.swing.JComboBox();
        periodicidad_donaciones_etiq3 = new javax.swing.JLabel();
        periodicidad_donaciones_input3 = new javax.swing.JTextField();
        cuantia_etiq3 = new javax.swing.JLabel();
        cuantia_input3 = new javax.swing.JTextField();
        bmodificarFecha = new javax.swing.JToggleButton();
        bmodificartperiodicidad = new javax.swing.JToggleButton();

        setMaximumSize(null);
        setMinimumSize(null);

        dni_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dni_etiq3.setText("DNI:");

        dni_input3.setBackground(new java.awt.Color(255, 204, 204));
        dni_input3.setEditable(false);
        dni_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dni_input3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dni_input3.setMaximumSize(new java.awt.Dimension(220, 50));
        dni_input3.setMinimumSize(new java.awt.Dimension(50, 30));
        dni_input3.setPreferredSize(null);
        dni_input3.setVerifyInputWhenFocusTarget(false);

        nombre_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre_etiq3.setText("Nombre:");

        nombre_input3.setBackground(new java.awt.Color(255, 204, 204));
        nombre_input3.setEditable(false);
        nombre_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre_input3.setMaximumSize(null);

        apellidos_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apellidos_etiq3.setText("Apellidos:");

        apellidos_input3.setBackground(new java.awt.Color(255, 204, 204));
        apellidos_input3.setEditable(false);
        apellidos_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tipo_donante_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipo_donante_etiq3.setText("Tipo donante:");

        tipo_donante_input3.setBackground(new java.awt.Color(255, 204, 204));
        tipo_donante_input3.setEditable(false);
        tipo_donante_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        fecha_nacimiento_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fecha_nacimiento_etiq3.setText("Fecha nacimiento:");

        dia_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dia_input3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mes_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mes_input3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        anio_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        anio_input3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        localidad_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        localidad_etiq3.setText("Localidad:");

        localidad_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        localidad_input3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                localidad_input3localidad_inputMouseClicked(evt);
            }
        });
        localidad_input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidad_input3ActionPerformed(evt);
            }
        });

        telefono_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefono_etiq3.setText("Telefono:");

        telefono_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefono_input3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefono_input3telefono_inputMouseClicked(evt);
            }
        });
        telefono_input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono_input3ActionPerformed(evt);
            }
        });

        email_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_etiq3.setText("Email:");

        email_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_input3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                email_input3email_inputMouseClicked(evt);
            }
        });
        email_input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_input3ActionPerformed(evt);
            }
        });

        fecha_inscripcion_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fecha_inscripcion_etiq3.setText("Fecha inscripción:");

        fecha_inscripcion_input3.setBackground(new java.awt.Color(255, 204, 204));
        fecha_inscripcion_input3.setEditable(false);
        fecha_inscripcion_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        observaciones_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        observaciones_etiq3.setText("Observaciones:");

        observaciones_input3.setBackground(new java.awt.Color(255, 204, 204));
        observaciones_input3.setColumns(20);
        observaciones_input3.setEditable(false);
        observaciones_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        observaciones_input3.setRows(5);
        jScrollPane7.setViewportView(observaciones_input3);

        tipo_periodicidad_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipo_periodicidad_etiq3.setText("Tipo periodicidad:");

        tipo_periodicidad_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipo_periodicidad_input3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguna", "Días", "Meses", "Años" }));

        periodicidad_donaciones_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        periodicidad_donaciones_etiq3.setText("Periodicidad:");

        periodicidad_donaciones_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        periodicidad_donaciones_input3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                periodicidad_donaciones_input3periodicidad_donaciones_inputMouseClicked(evt);
            }
        });
        periodicidad_donaciones_input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodicidad_donaciones_input3ActionPerformed(evt);
            }
        });

        cuantia_etiq3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cuantia_etiq3.setText("Importe:");

        cuantia_input3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cuantia_input3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuantia_input3cuantia_inputMouseClicked(evt);
            }
        });
        cuantia_input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuantia_input3ActionPerformed(evt);
            }
        });

        bmodificarFecha.setBackground(new java.awt.Color(153, 153, 255));
        bmodificarFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bmodificarFecha.setText("Modificar");
        bmodificarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificarFechaActionPerformed(evt);
            }
        });

        bmodificartperiodicidad.setBackground(new java.awt.Color(153, 153, 255));
        bmodificartperiodicidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bmodificartperiodicidad.setText("Modificar");
        bmodificartperiodicidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificartperiodicidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tipo_periodicidad_etiq3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipo_periodicidad_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bmodificartperiodicidad)
                        .addGap(18, 18, 18)
                        .addComponent(periodicidad_donaciones_etiq3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(periodicidad_donaciones_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cuantia_etiq3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuantia_input3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fecha_nacimiento_etiq3)
                        .addGap(18, 18, 18)
                        .addComponent(dia_input3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)
                        .addComponent(mes_input3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(anio_input3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80)
                        .addComponent(bmodificarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(apellidos_etiq3)
                                .addGap(18, 18, 18)
                                .addComponent(apellidos_input3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dni_etiq3)
                                .addGap(18, 18, 18)
                                .addComponent(dni_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nombre_etiq3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipo_donante_etiq3)
                                .addGap(27, 27, 27)
                                .addComponent(tipo_donante_input3))
                            .addComponent(nombre_input3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(email_etiq3)
                                .addGap(18, 18, 18)
                                .addComponent(email_input3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(localidad_etiq3)
                                .addGap(18, 18, 18)
                                .addComponent(localidad_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(telefono_etiq3)
                                .addGap(18, 18, 18)
                                .addComponent(telefono_input3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fecha_inscripcion_etiq3)
                                .addGap(18, 18, 18)
                                .addComponent(fecha_inscripcion_input3))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(observaciones_etiq3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dni_etiq3)
                    .addComponent(nombre_etiq3)
                    .addComponent(nombre_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos_etiq3)
                    .addComponent(apellidos_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo_donante_etiq3)
                    .addComponent(tipo_donante_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha_nacimiento_etiq3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dia_input3)
                    .addComponent(mes_input3)
                    .addComponent(anio_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmodificarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localidad_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localidad_etiq3)
                    .addComponent(telefono_etiq3)
                    .addComponent(telefono_input3))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_etiq3)
                    .addComponent(email_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_inscripcion_etiq3)
                    .addComponent(fecha_inscripcion_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(observaciones_etiq3)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bmodificartperiodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo_periodicidad_etiq3)
                    .addComponent(periodicidad_donaciones_etiq3)
                    .addComponent(periodicidad_donaciones_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuantia_etiq3)
                    .addComponent(tipo_periodicidad_input3)
                    .addComponent(cuantia_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void localidad_input3localidad_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localidad_input3localidad_inputMouseClicked
        // TODO add your handling code here:
        tv.asociarCampo(localidad_input3);
        tv.activar();
    }//GEN-LAST:event_localidad_input3localidad_inputMouseClicked

    private void telefono_input3telefono_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefono_input3telefono_inputMouseClicked
        // TODO add your handling code here:
        tv.asociarCampo(telefono_input3);
        tv.activar();
    }//GEN-LAST:event_telefono_input3telefono_inputMouseClicked

    private void email_input3email_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_input3email_inputMouseClicked
        // TODO add your handling code here:
        
        tv.asociarCampo(email_input3);
        tv.activar();
    }//GEN-LAST:event_email_input3email_inputMouseClicked

    private void periodicidad_donaciones_input3periodicidad_donaciones_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_periodicidad_donaciones_input3periodicidad_donaciones_inputMouseClicked
        // TODO add your handling code here:
        
        tv.asociarCampo(periodicidad_donaciones_input3);
        tv.activar();
    }//GEN-LAST:event_periodicidad_donaciones_input3periodicidad_donaciones_inputMouseClicked

    private void cuantia_input3cuantia_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuantia_input3cuantia_inputMouseClicked
        // TODO add your handling code here:
        
        tv.asociarCampo(cuantia_input3);
        tv.activar();
    }//GEN-LAST:event_cuantia_input3cuantia_inputMouseClicked

    private void localidad_input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidad_input3ActionPerformed
        // TODO add your handling code here:
        Object localidad = localidad_input3.getText();
        
        if(((String) localidad).compareTo("") != 0)
            diaketas.diaketas.ong.gestorDonantes.modificarElemento(localidad, 1);
        else
            JOptionPane.showMessageDialog(this, "No se ha introducido una localidad", "Localidad", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_localidad_input3ActionPerformed

    private void telefono_input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono_input3ActionPerformed
        // TODO add your handling code here:
        Object telefono = new Integer(Integer.parseInt(telefono_input3.getText()));
        
        
        if(((Integer) telefono).toString().length() == 9)
            diaketas.diaketas.ong.gestorDonantes.modificarElemento(telefono,2);
        else
            JOptionPane.showMessageDialog(this, "El telefono introducido no es correcto", "Telefono", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_telefono_input3ActionPerformed

    private void email_input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_input3ActionPerformed
        // TODO add your handling code here:
        Object email = email_input3.getText();
        
        if(ValidarCampos.ValidarCampos.isEmail((String) email))
            diaketas.diaketas.ong.gestorDonantes.modificarElemento(email,3);
        else
            JOptionPane.showMessageDialog(this, "El email introducido no es correcto", "Email", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_email_input3ActionPerformed

    private void bmodificartperiodicidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificartperiodicidadActionPerformed
        // TODO add your handling code here:
        Object tperiodicidad = tipo_periodicidad_input3.getSelectedItem().toString();
        
        diaketas.diaketas.ong.gestorDonantes.modificarElemento(tperiodicidad,4);
    }//GEN-LAST:event_bmodificartperiodicidadActionPerformed

    private void periodicidad_donaciones_input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodicidad_donaciones_input3ActionPerformed
        // TODO add your handling code here:
        Object periodicidad = new Integer(Integer.parseInt(periodicidad_donaciones_input3.getText()));
        
        if(((Integer) periodicidad).intValue() > 0)
            diaketas.diaketas.ong.gestorDonantes.modificarElemento(periodicidad,5);
        else
            JOptionPane.showMessageDialog(this, "La periodicidad no se ha introducido correctamente. Debe ser mayor que 0.", "Periodicidad", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_periodicidad_donaciones_input3ActionPerformed

    private void cuantia_input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuantia_input3ActionPerformed
        // TODO add your handling code here:
        Object cuantia = new Double(Double.parseDouble(cuantia_input3.getText()));
        
        if(((Double) cuantia).doubleValue() > 0)
            diaketas.diaketas.ong.gestorDonantes.modificarElemento(cuantia,6);
        else
            JOptionPane.showMessageDialog(this, "La cuantia de las donaciones introducida no es correcta. Debe ser mayor que 0.", "Cuantia", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_cuantia_input3ActionPerformed

    private void bmodificarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificarFechaActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy");
        Object fecha_nac;
        try {
            fecha_nac = formateador.parse(String.valueOf((Integer) dia_input3.getSelectedItem()) + "/" + String.valueOf((Integer) mes_input3.getSelectedItem()) + "/" + String.valueOf((Integer) anio_input3.getSelectedItem()));
            diaketas.diaketas.ong.gestorDonantes.modificarElemento(fecha_nac, 0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bmodificarFechaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox anio_input3;
    private javax.swing.JLabel apellidos_etiq3;
    private javax.swing.JTextField apellidos_input3;
    private javax.swing.JToggleButton bmodificarFecha;
    private javax.swing.JToggleButton bmodificartperiodicidad;
    private javax.swing.JLabel cuantia_etiq3;
    private javax.swing.JTextField cuantia_input3;
    private javax.swing.JComboBox dia_input3;
    private javax.swing.JLabel dni_etiq3;
    private javax.swing.JTextField dni_input3;
    private javax.swing.JLabel email_etiq3;
    private javax.swing.JTextField email_input3;
    private javax.swing.JLabel fecha_inscripcion_etiq3;
    private javax.swing.JTextField fecha_inscripcion_input3;
    private javax.swing.JLabel fecha_nacimiento_etiq3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel localidad_etiq3;
    private javax.swing.JTextField localidad_input3;
    private javax.swing.JComboBox mes_input3;
    private javax.swing.JLabel nombre_etiq3;
    private javax.swing.JTextField nombre_input3;
    private javax.swing.JLabel observaciones_etiq3;
    private javax.swing.JTextArea observaciones_input3;
    private javax.swing.JLabel periodicidad_donaciones_etiq3;
    private javax.swing.JTextField periodicidad_donaciones_input3;
    private javax.swing.JLabel telefono_etiq3;
    private javax.swing.JTextField telefono_input3;
    private javax.swing.JLabel tipo_donante_etiq3;
    private javax.swing.JTextField tipo_donante_input3;
    private javax.swing.JLabel tipo_periodicidad_etiq3;
    private javax.swing.JComboBox tipo_periodicidad_input3;
    // End of variables declaration//GEN-END:variables
}
