/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diaketas.UI.Movil;

import diaketas.ConexionBD;
import diaketas.Modelo.ONG.Movimiento;
import diaketas.UI.UI;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MIGUEL
 */
public class jListarAportesM extends javax.swing.JPanel {

    /**
     * Creates new form jListarAportesM
     */
    public jListarAportesM() {
        initComponents();
        
        DefaultTableModel tabla = (DefaultTableModel) listadoMovimiento.getModel();
        tabla.setRowCount(0);
        
        int nMovimientos = diaketas.UI.Movil.UI.movimientosEncontrados.size();
        
        if(nMovimientos != 0) {
            //Oferta oferta_actual;
            Object[] fila = new Object[6];
            //for(int i = 0 ; i < nMovimientos ; i++) {
                //oferta_actual = ofertasEncontradas.get(i);
            
            for(Movimiento m : diaketas.UI.Movil.UI.movimientosEncontrados){
                fila[0] = m.obtenerCuantia();
                fila[1] = m.obtenerFecha();
                fila[2] = m.obtenerTipoMovimiento();
                //fila[4] = m.obtenerInvolucrado();

                
                tabla.addRow(fila);
            }

        }

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoMovimiento = new javax.swing.JTable();
        salir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 102));
        setMaximumSize(new java.awt.Dimension(409, 350));
        setMinimumSize(new java.awt.Dimension(409, 350));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("Listar aportes");

        jScrollPane1.setMaximumSize(new java.awt.Dimension(409, 350));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(409, 350));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(409, 350));

        listadoMovimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listadoMovimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(listadoMovimiento);

        salir.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:

        diaketas.UI.Movil.UI.cl.show(diaketas.UI.Movil.UI.jPrincipal, "SeleccionarOpcion");
    }//GEN-LAST:event_salirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listadoMovimiento;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
