/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diaketas.UI.Movil;

/**
 *
 * @author klyone
 */
public class jModificarDatos extends javax.swing.JPanel {
    
    jSTeclado teclado_virtual = null;

    /**
     * Creates new form jModificarDatos
     */
    public jModificarDatos() {
        initComponents();
        teclado_virtual = new jSTeclado(localidad_input);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        localidad_etiq = new javax.swing.JLabel();
        mes_input = new javax.swing.JComboBox();
        anio_input = new javax.swing.JComboBox();
        tipo_donante_input = new javax.swing.JTextField();
        dia_input = new javax.swing.JComboBox();
        nombre_input = new javax.swing.JTextField();
        apellidos_input = new javax.swing.JTextField();
        dni_input = new javax.swing.JTextField();
        localidad_input = new javax.swing.JTextField();
        telefono_etiq = new javax.swing.JLabel();
        telefono_input = new javax.swing.JTextField();
        email_etiq = new javax.swing.JLabel();
        email_input = new javax.swing.JTextField();
        fecha_inscripcion_etiq = new javax.swing.JLabel();
        fecha_inscripcion_input = new javax.swing.JTextField();
        observaciones_etiq = new javax.swing.JLabel();
        nombre_etiq = new javax.swing.JLabel();
        dni_etiq = new javax.swing.JLabel();
        fecha_nacimiento_etiq = new javax.swing.JLabel();
        tipo_donante_etiq = new javax.swing.JLabel();
        apellidos_etiq = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        observaciones_input = new javax.swing.JTextArea();
        tipo_periodicidad_etiq = new javax.swing.JLabel();
        periodicidad_donaciones_etiq = new javax.swing.JLabel();
        cuantia_etiq = new javax.swing.JLabel();
        tipo_periodicidad_input = new javax.swing.JComboBox();
        periodicidad_donaciones_input = new javax.swing.JTextField();
        cuantia_input = new javax.swing.JTextField();
        bmodificar = new javax.swing.JButton();

        setAutoscrolls(true);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setPreferredSize(new java.awt.Dimension(434, 920));

        localidad_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        localidad_etiq.setText("Localidad:");

        mes_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mes_input.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        anio_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        anio_input.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        tipo_donante_input.setBackground(new java.awt.Color(255, 204, 204));
        tipo_donante_input.setEditable(false);
        tipo_donante_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dia_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dia_input.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        nombre_input.setBackground(new java.awt.Color(255, 204, 204));
        nombre_input.setEditable(false);
        nombre_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        apellidos_input.setBackground(new java.awt.Color(255, 204, 204));
        apellidos_input.setEditable(false);
        apellidos_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dni_input.setBackground(new java.awt.Color(255, 204, 204));
        dni_input.setEditable(false);
        dni_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        localidad_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        localidad_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                localidad_inputMouseClicked(evt);
            }
        });

        telefono_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefono_etiq.setText("Telefono:");

        telefono_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefono_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefono_inputMouseClicked(evt);
            }
        });

        email_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_etiq.setText("Email:");

        email_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                email_inputMouseClicked(evt);
            }
        });

        fecha_inscripcion_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fecha_inscripcion_etiq.setText("Fecha inscripción:");

        fecha_inscripcion_input.setBackground(new java.awt.Color(255, 204, 204));
        fecha_inscripcion_input.setEditable(false);
        fecha_inscripcion_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        observaciones_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        observaciones_etiq.setText("Observaciones:");

        nombre_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre_etiq.setText("Nombre:");

        dni_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dni_etiq.setText("DNI:");

        fecha_nacimiento_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fecha_nacimiento_etiq.setText("Fecha nacimiento:");

        tipo_donante_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipo_donante_etiq.setText("Tipo de donante:");

        apellidos_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apellidos_etiq.setText("Apellidos:");

        observaciones_input.setBackground(new java.awt.Color(255, 204, 204));
        observaciones_input.setColumns(20);
        observaciones_input.setEditable(false);
        observaciones_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        observaciones_input.setRows(5);
        jScrollPane4.setViewportView(observaciones_input);

        tipo_periodicidad_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipo_periodicidad_etiq.setText("Tipo periodicidad:");

        periodicidad_donaciones_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        periodicidad_donaciones_etiq.setText("Periodicidad:");

        cuantia_etiq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cuantia_etiq.setText("Cuantía:");

        tipo_periodicidad_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipo_periodicidad_input.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguna", "Días", "Meses", "Años" }));

        periodicidad_donaciones_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        periodicidad_donaciones_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                periodicidad_donaciones_inputMouseClicked(evt);
            }
        });

        cuantia_input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cuantia_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuantia_inputMouseClicked(evt);
            }
        });

        bmodificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bmodificar.setText("Modificar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(bmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(observaciones_etiq)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(dia_input, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(mes_input, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(anio_input, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cuantia_etiq)
                                                .addComponent(periodicidad_donaciones_etiq)
                                                .addComponent(tipo_periodicidad_etiq))
                                            .addGap(32, 32, 32)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cuantia_input, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(periodicidad_donaciones_input, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tipo_periodicidad_input, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jScrollPane4)))))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(fecha_inscripcion_etiq)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecha_inscripcion_input, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tipo_donante_etiq)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dni_etiq)
                                .addComponent(nombre_etiq)
                                .addComponent(apellidos_etiq))
                            .addGap(95, 95, 95)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(apellidos_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dni_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nombre_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tipo_donante_input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(email_etiq)
                                    .addGap(122, 122, 122))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fecha_nacimiento_etiq)
                                        .addComponent(localidad_etiq)
                                        .addComponent(telefono_etiq))
                                    .addGap(28, 28, 28)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telefono_input, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(localidad_input, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dia_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(anio_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mes_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(observaciones_etiq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_periodicidad_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo_periodicidad_etiq))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(periodicidad_donaciones_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodicidad_donaciones_etiq))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuantia_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuantia_etiq))
                .addGap(35, 35, 35)
                .addComponent(bmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dni_etiq)
                        .addComponent(dni_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nombre_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombre_etiq))
                    .addGap(25, 25, 25)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(apellidos_etiq)
                        .addComponent(apellidos_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tipo_donante_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tipo_donante_etiq))
                    .addGap(28, 28, 28)
                    .addComponent(fecha_nacimiento_etiq)
                    .addGap(27, 27, 27)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(localidad_etiq)
                        .addComponent(localidad_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(telefono_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telefono_etiq))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(email_etiq))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fecha_inscripcion_etiq)
                        .addComponent(fecha_inscripcion_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(477, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void localidad_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localidad_inputMouseClicked
        // TODO add your handling code here:
        teclado_virtual.asociarCampo(localidad_input);
        teclado_virtual.activar();
    }//GEN-LAST:event_localidad_inputMouseClicked

    private void telefono_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefono_inputMouseClicked
        // TODO add your handling code here:
        teclado_virtual.asociarCampo(telefono_input);
        teclado_virtual.activar();
    }//GEN-LAST:event_telefono_inputMouseClicked

    private void email_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_inputMouseClicked
        // TODO add your handling code here:
        teclado_virtual.asociarCampo(email_input);
        teclado_virtual.activar();
    }//GEN-LAST:event_email_inputMouseClicked

    private void periodicidad_donaciones_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_periodicidad_donaciones_inputMouseClicked
        // TODO add your handling code here:
        teclado_virtual.asociarCampo(periodicidad_donaciones_input);
        teclado_virtual.activar();
    }//GEN-LAST:event_periodicidad_donaciones_inputMouseClicked

    private void cuantia_inputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuantia_inputMouseClicked
        // TODO add your handling code here:
        teclado_virtual.asociarCampo(cuantia_input);
        teclado_virtual.activar();
    }//GEN-LAST:event_cuantia_inputMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox anio_input;
    private javax.swing.JLabel apellidos_etiq;
    private javax.swing.JTextField apellidos_input;
    private javax.swing.JButton bmodificar;
    private javax.swing.JLabel cuantia_etiq;
    private javax.swing.JTextField cuantia_input;
    private javax.swing.JComboBox dia_input;
    private javax.swing.JLabel dni_etiq;
    private javax.swing.JTextField dni_input;
    private javax.swing.JLabel email_etiq;
    private javax.swing.JTextField email_input;
    private javax.swing.JLabel fecha_inscripcion_etiq;
    private javax.swing.JTextField fecha_inscripcion_input;
    private javax.swing.JLabel fecha_nacimiento_etiq;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel localidad_etiq;
    private javax.swing.JTextField localidad_input;
    private javax.swing.JComboBox mes_input;
    private javax.swing.JLabel nombre_etiq;
    private javax.swing.JTextField nombre_input;
    private javax.swing.JLabel observaciones_etiq;
    private javax.swing.JTextArea observaciones_input;
    private javax.swing.JLabel periodicidad_donaciones_etiq;
    private javax.swing.JTextField periodicidad_donaciones_input;
    private javax.swing.JLabel telefono_etiq;
    private javax.swing.JTextField telefono_input;
    private javax.swing.JLabel tipo_donante_etiq;
    private javax.swing.JTextField tipo_donante_input;
    private javax.swing.JLabel tipo_periodicidad_etiq;
    private javax.swing.JComboBox tipo_periodicidad_input;
    // End of variables declaration//GEN-END:variables
}
