package diaketas.UI.Movil;

import diaketas.UI.Movil.jTeclado;
import javax.swing.JTextField;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author klyone
 */
public class jSTeclado extends javax.swing.JFrame {

    /**
     * Creates new form jSTeclado
     */
    public jSTeclado() {
        initComponents();
        this.setResizable(false);
    }
    
    public jSTeclado(JTextField t) {
        campo_texto = t;
        initComponents();
        this.setResizable(false);
    }
    
    public void activar() {
        this.setVisible(true);
    }
    
    public void desactivar() {
        this.setVisible(false);
    }
    
    public void asociarCampo(JTextField t) {
        campo_texto = t;
        jTeclado1.asociarCampo(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTeclado1 = new jTeclado(campo_texto);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTeclado1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTeclado1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jTeclado jTeclado1;
    // End of variables declaration//GEN-END:variables
    private JTextField campo_texto = null;
}
