/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diaketas.UI.Empleo;

import diaketas.UI.UI;
import javax.swing.JPanel;

/**
 *
 * @author trabajo
 */
public class jAsociarBeneficiario extends javax.swing.JPanel {

    /**
     * Creates new form jAsociarBeneficiario
     */
    public jAsociarBeneficiario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jTitulo1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTitulo2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        panel_busqueda = new javax.swing.JPanel();
        panel_parametros_busqueda = new javax.swing.JPanel();
        dni_beneficiario_etiq = new javax.swing.JLabel();
        dni_beneficiario_input = new javax.swing.JTextField();
        panel_botones_control = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        botonBuscarOfertas = new javax.swing.JButton();
        botonContinuar = new javax.swing.JButton();
        jTitulo3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadoOfertasBeneficiario = new javax.swing.JList();

        setBackground(new java.awt.Color(233, 225, 242));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diaketas/Iconos/empleo.png"))); // NOI18N

        jTitulo1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTitulo1.setText("Ofertas de empleo");

        jTitulo2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTitulo2.setText("Buscar un beneficiario para ser asociado a la oferta");

        panel_busqueda.setBackground(new java.awt.Color(255, 255, 255));
        panel_busqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panel_parametros_busqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dni_beneficiario_etiq.setText("DNI beneficiario:");

        dni_beneficiario_input.setColumns(9);
        dni_beneficiario_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dni_beneficiario_inputKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel_parametros_busquedaLayout = new javax.swing.GroupLayout(panel_parametros_busqueda);
        panel_parametros_busqueda.setLayout(panel_parametros_busquedaLayout);
        panel_parametros_busquedaLayout.setHorizontalGroup(
            panel_parametros_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_parametros_busquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dni_beneficiario_etiq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dni_beneficiario_input, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_parametros_busquedaLayout.setVerticalGroup(
            panel_parametros_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_parametros_busquedaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel_parametros_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni_beneficiario_etiq)
                    .addComponent(dni_beneficiario_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panel_botones_control.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonBuscarOfertas.setText("Buscar");
        botonBuscarOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarOfertasActionPerformed(evt);
            }
        });

        botonContinuar.setText("Continuar");
        botonContinuar.setEnabled(false);
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_botones_controlLayout = new javax.swing.GroupLayout(panel_botones_control);
        panel_botones_control.setLayout(panel_botones_controlLayout);
        panel_botones_controlLayout.setHorizontalGroup(
            panel_botones_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_botones_controlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_botones_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBuscarOfertas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonContinuar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_botones_controlLayout.setVerticalGroup(
            panel_botones_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_botones_controlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonBuscarOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTitulo3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTitulo3.setForeground(new java.awt.Color(242, 9, 9));
        jTitulo3.setText("Error: No existe ningún beneficiario");

        javax.swing.GroupLayout panel_busquedaLayout = new javax.swing.GroupLayout(panel_busqueda);
        panel_busqueda.setLayout(panel_busquedaLayout);
        panel_busquedaLayout.setHorizontalGroup(
            panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_busquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_parametros_busqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_botones_control, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_busquedaLayout.createSequentialGroup()
                        .addComponent(jTitulo3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_busquedaLayout.setVerticalGroup(
            panel_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_busquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_parametros_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTitulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(panel_botones_control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        listadoOfertasBeneficiario.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Oferta1 asociada al beneficiario", "Oferta 2 asociada al beneficiario", "Oferta3 asociada al beneficiario" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listadoOfertasBeneficiario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listadoOfertasBeneficiario.setFocusable(false);
        jScrollPane1.setViewportView(listadoOfertasBeneficiario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTitulo2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel17)
                                .addGap(69, 69, 69)
                                .addComponent(jTitulo1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panel_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jTitulo1))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_busqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dni_beneficiario_inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dni_beneficiario_inputKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_dni_beneficiario_inputKeyTyped

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        UI.cl.show(UI.jPrincipal, "Empleo");
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonBuscarOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarOfertasActionPerformed
        // TODO add your handling code here:
        botonContinuar.setEnabled(true);
    }//GEN-LAST:event_botonBuscarOfertasActionPerformed

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        // TODO add your handling code here:
       panel = new jAsociarBeneficiario2();

       UI.jPrincipal.add("AsociarBeneficiarioOferta2", panel);
       UI.cl.show(UI.jPrincipal, "AsociarBeneficiarioOferta2");
    }//GEN-LAST:event_botonContinuarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarOfertas;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JLabel dni_beneficiario_etiq;
    private javax.swing.JTextField dni_beneficiario_input;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jTitulo1;
    private javax.swing.JLabel jTitulo2;
    private javax.swing.JLabel jTitulo3;
    private javax.swing.JList listadoOfertasBeneficiario;
    private javax.swing.JPanel panel_botones_control;
    private javax.swing.JPanel panel_busqueda;
    private javax.swing.JPanel panel_parametros_busqueda;
    // End of variables declaration//GEN-END:variables

    private JPanel panel;
}

