/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diaketas.UI.Empleo;

import ValidarCampos.ValidarCampos;
import diaketas.Modelo.Gestores.Gestor_de_ofertas;
import diaketas.Modelo.ONG.ONG;
import diaketas.Modelo.ONG.Oferta;
import diaketas.UI.UI;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * 
 * @author Cesar
 */
public class jEliminarOferta extends javax.swing.JPanel {

    jEliminacionCorrecta confirmarEliminacion;
    JPanel panel;
    /**
     * Creates new form jConsultarMovimiento
     */
    public jEliminarOferta() {
        initComponents();
        
        //Ponemos por defecto los datos del voluntario a modificar
        
        Oferta datosOferta = ONG.gestorOfertas.consultarDatosOferta();
        /*
        Cod_Oferta.setText( Integer.toString(datosOferta.cod_oferta) );
        Concepto.setText( datosOferta.concepto );
        Activada.setText( Integer.toString(datosOferta.activo) );
        Poblacion.setText( datosOferta.poblacion );
        Num_vacantes.setText( Integer.toString(datosOferta.numero_vacantes) );
        Descripcion.setText( datosOferta.descripcion );
        Req_minimos.setText( datosOferta.requisitos_minimos );
        Tipo_contrato.setText( datosOferta.tipo_contrato );
        Jornada_laboral.setText( Integer.toString(datosOferta.jornada_laboral) );
        Salario.setText( Double.toString(datosOferta.salario) );
        DNI_donante.setText( datosOferta.NIF_CIF_Donante );
        Observaciones.setText( datosOferta.observaciones );
        
        
        // Representamos la fecha, pasandola de tipo Date a String
        SimpleDateFormat formatoFecha=new java.text.SimpleDateFormat("dd/MM/yy");
               
        Fecha.setText(formatoFecha.format(datosOferta.fecha) );*/

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        botonOK = new javax.swing.JButton();
        jTitulo2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jTitulo1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        NIF1 = new javax.swing.JTextField();
        Codigo_oferta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(233, 225, 242));
        setForeground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(32767, 500));
        setPreferredSize(new java.awt.Dimension(1100, 518));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        botonOK.setText("Eliminar");
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });

        jTitulo2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTitulo2.setText("Eliminar una oferta");

        jTitulo1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTitulo1.setText("Empleo");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diaketas/Iconos/empleo.png"))); // NOI18N

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel17.setText("DNI del voluntario actual");

        NIF1.setBackground(new java.awt.Color(255, 255, 153));
        NIF1.setColumns(9);
        NIF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NIF1KeyTyped(evt);
            }
        });

        Codigo_oferta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Codigo_oferta.setText("¿Está seguro de que desea eliminar esta oferta?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(jTitulo1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTitulo2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Codigo_oferta)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(NIF1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jTitulo1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Codigo_oferta)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonOK)
                    .addComponent(botonCancelar))
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed

        boolean exito;
        
        boolean error = ONG.gestorOfertas.eliminarOferta();

        if(!error)  //si no hay errores
        {
            exito=true;

            //ahora registro la operacion en el historial

            ONG.gestorOfertas.finEliminarOferta();

        }
        else    //si hay algun error...
        {
            exito=false;
        }
        
        if (exito) //si la operacion se ha realizado con exito y se habian introducido todos los datos
        {
            //MODIFICACION OFERTA REALIZADA
            confirmarEliminacion = new jEliminacionCorrecta();
            UI.jPrincipal.remove(confirmarEliminacion);
            UI.jPrincipal.add("ConfirmarModificacion", confirmarEliminacion);
            UI.cl.show(UI.jPrincipal, "ConfirmarModificacion");
        } else if (!exito) {
            JOptionPane.showMessageDialog(this, "No se ha podido realizar correctamente la eliminación.", "Error eliminación", JOptionPane.ERROR_MESSAGE);
        }
            
        //continuar
        
        //UI.cl.show(UI.jPrincipal, "Empleo");
    }//GEN-LAST:event_botonOKActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
     
        double fuente = 13 + (this.getSize().width - 1262) / 30;
        for (int i = 0; i < this.getComponentCount(); i++) {
            this.getComponent(i).setFont(new Font("Courier", Font.BOLD, (int) fuente));
        }

        jTitulo1.setFont(new Font("Courier", Font.BOLD, (int) fuente+12));
        jTitulo2.setFont(new Font("Courier", Font.BOLD, (int) fuente+2));
        
        /*Codigo_oferta.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
        Concepto.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
        Fecha.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
        Activada.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
        Poblacion.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
        Num_vacantes.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
        Req_minimos.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
        Tipo_contrato.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
        Jornada_laboral.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
        Salario.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
        DNI_donante.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
        Descripcion.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
        Observaciones.setFont(new Font("Courier", Font.PLAIN, (int) fuente));*/
        
    }//GEN-LAST:event_formComponentResized

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        
        UI.cl.show(UI.jPrincipal, "Empleo");
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void NIF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NIF1KeyTyped
        // TODO add your handling code here:
        if (NIF1.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_NIF1KeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Codigo_oferta;
    private javax.swing.JTextField NIF1;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonOK;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel jTitulo1;
    private javax.swing.JLabel jTitulo2;
    // End of variables declaration//GEN-END:variables
}
