/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diaketas.UI.Beneficiarios;

import diaketas.Modelo.ONG.Familiar;
import diaketas.Modelo.ONG.ONG;
import diaketas.UI.UI;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kesada
 */
public class jListarFamiliar extends javax.swing.JPanel {

    JPanel panel;
    String jPanelAnterior, jPanelSiguiente;
    ArrayList <Familiar> familiares;
    
    /**
     * Creates new form jAltaFamiliar
     * @param jPanelAnterior
     * @param jPanelSiguiente  
     */
    public jListarFamiliar(String jPanelAnterior, String jPanelSiguiente) {
        this.jPanelAnterior = jPanelAnterior;
        this.jPanelSiguiente = jPanelSiguiente;
        
        /*Inicializamos*/
        initComponents();
        
        /* inicioModificarFamiliar()*/
        /* inicioConsultarFamiliar()*/
        /*Mostramos inicioMostrarFamiliar*/
        familiares = ONG.gestorBeneficiarios.iniciarConsultarFamiliar();


        /*Mostramos los familiares*/
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < familiares.size();i++){
            modelo.addElement((String)familiares.get(i).Nombre_Apellidos);}
        listaFamiliares.setModel(modelo);
        if (familiares.isEmpty()){
            botonOK.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitulo2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        botonOK = new javax.swing.JButton();
        botonCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFamiliares = new javax.swing.JList();
        jLabel17 = new javax.swing.JLabel();
        jTitulo1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(223, 232, 249));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jTitulo2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTitulo2.setText("Familiares");

        jLabel2.setText("Seleccione un familiar");

        botonOK.setText("Seleccionar");
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });

        botonCancel.setText("Cancelar");
        botonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaFamiliares);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diaketas/Iconos/beneficiarios.png"))); // NOI18N

        jTitulo1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTitulo1.setText("Beneficiarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel17)
                        .addGap(69, 69, 69)
                        .addComponent(jTitulo1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTitulo2, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(0, 113, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(botonOK)
                .addGap(18, 18, 18)
                .addComponent(botonCancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jTitulo1))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonOK)
                    .addComponent(botonCancel))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed
    
        if (listaFamiliares.getSelectedIndex() != -1){
            if (jPanelSiguiente.compareTo("BajaFamiliar") ==0){
                
                /*Pasamos al formulario de Baja el nombre del familiar*/
                panel = new jBajaFamiliar(jPanelAnterior, (String) listaFamiliares.getSelectedValue());
                
                ONG.gestorBeneficiarios.seleccionarFamiliar(familiares.get(listaFamiliares.getSelectedIndex()).Nombre_Apellidos,
                        familiares.get(listaFamiliares.getSelectedIndex()).Fecha_Nacimiento);
                
                UI.jPrincipal.add(jPanelSiguiente, panel); 
                UI.cl.show(UI.jPrincipal, "BajaFamiliar");
                
            }else if (jPanelSiguiente.compareTo("ConsultarFamiliar") ==0){
 
                /*Pasamos al formulario de Modificar el nombre del familiar*/
                panel = new jConsultarFamiliar(jPanelAnterior, familiares.get(listaFamiliares.getSelectedIndex()).Nombre_Apellidos,
                        familiares.get(listaFamiliares.getSelectedIndex()).Fecha_Nacimiento);
                
                UI.jPrincipal.add(jPanelSiguiente, panel); 
                UI.cl.show(UI.jPrincipal, "ConsultarFamiliar");  
                
            }else{
                
                /*Pasamos al formulario de Modificar el nombre del familiar*/
                panel = new jModificarFamiliar(jPanelAnterior, familiares.get(listaFamiliares.getSelectedIndex()).Nombre_Apellidos,
                        familiares.get(listaFamiliares.getSelectedIndex()).Fecha_Nacimiento);
                
                UI.jPrincipal.add(jPanelSiguiente, panel); 
                UI.cl.show(UI.jPrincipal, "ModificarFamiliar");  
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un familiar.", "Familiar", JOptionPane.ERROR_MESSAGE);

        }    
    }//GEN-LAST:event_botonOKActionPerformed

    private void botonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelActionPerformed
            UI.cl.show(UI.jPrincipal, jPanelAnterior);
            // TODO add your handling code here:
    }//GEN-LAST:event_botonCancelActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        int ancho, alto;
        ancho = this.getSize().width;
        alto = this.getSize().height;

        double fuente = 13 + (ancho - 1262) / 30;
        for (int i = 0; i < this.getComponentCount(); i++) {
            this.getComponent(i).setFont(new Font("Courier", Font.BOLD, (int) fuente));
        }
        
        jTitulo1.setFont(new Font("Courier", Font.BOLD, (int) fuente+12));
        jTitulo2.setFont(new Font("Courier", Font.BOLD, (int) fuente+2));
        
        listaFamiliares.setFont(new Font("Courier", Font.PLAIN, (int) fuente));
    }//GEN-LAST:event_formComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancel;
    private javax.swing.JButton botonOK;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jTitulo1;
    private javax.swing.JLabel jTitulo2;
    private javax.swing.JList listaFamiliares;
    // End of variables declaration//GEN-END:variables
}
