/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diaketas.UI.Beneficiarios;

import ValidarCampos.ValidarCampos;
import diaketas.Modelo.ONG.Beneficiario;
import diaketas.Modelo.ONG.ONG;
import diaketas.UI.UI;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kesada
 */
public class jModificarBeneficiario extends javax.swing.JPanel {

    JPanel panel;
    Beneficiario datosBeneficiario;
    int fase;
    
    /**
     * Creates new form jAltaBeneficiario
     * @param datosBeneficiario 
     */
    public jModificarBeneficiario(Beneficiario datosBeneficiario) {
        this.datosBeneficiario = datosBeneficiario;
        
        /*Iniciamos la interfaz*/
        initComponents();
               
        fase = 0;
        
        /*Mostramos los datos de beneficiario*/
        NIF.setText(datosBeneficiario.NIF_CIF);
        Nombre.setText(datosBeneficiario.Nombre);
        Email.setText(datosBeneficiario.Email);
        Apellidos.setText(datosBeneficiario.Apellidos);
        
        Nacionalidad.setText(datosBeneficiario.Nacionalidad);
        Estado_Civil.setSelectedItem(datosBeneficiario.Estado_civil);
        Domicilio.setText(datosBeneficiario.Domicilio);
        if (datosBeneficiario.Expediente != 0)
            Expediente.setText(Integer.toString(datosBeneficiario.Expediente));
        if (datosBeneficiario.Codigo_Postal != 0)
            Codigo_Postal.setText(Integer.toString(datosBeneficiario.Codigo_Postal));
        Localidad.setText(datosBeneficiario.Localidad);
        if (datosBeneficiario.Telefono != 0)
            Telefono.setText(Integer.toString(datosBeneficiario.Telefono));
        Tipo_Vivienda.setText(datosBeneficiario.Tipo_Vivienda);
        if (datosBeneficiario.Precio_Vivienda != 0.0)
            Precio_Vivienda.setText(Double.toString(datosBeneficiario.Precio_Vivienda));
        Motivo.setText(datosBeneficiario.Motivo);
        Observaciones_Datos_Personales.setText(datosBeneficiario.Observaciones_Datos_Personales);
        Observaciones_Familiares.setText(datosBeneficiario.Observaciones_Familiares);        
        Observaciones_Vivienda.setText(datosBeneficiario.Observaciones_Vivienda);
        Ciudad_Nacimiento.setText(datosBeneficiario.Ciudad_Nacimiento);
        Situacion_Economica.setText(datosBeneficiario.Situacion_Economica);
        Nivel_Estudios.setText(datosBeneficiario.Nivel_Estudios);
        Profesion.setText(datosBeneficiario.Profesion);
        Experiencia_Laboral.setText(datosBeneficiario.Experiencia_Laboral);
        
        /* Representamos la fecha*/
        SimpleDateFormat formatoFecha=new java.text.SimpleDateFormat("dd/MM/yy");
        Fecha_Nacimiento.setText(formatoFecha.format(datosBeneficiario.FechaNac));
    }
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tipo_Vivienda = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Observaciones_Datos_Personales_SB = new javax.swing.JScrollPane();
        Observaciones_Datos_Personales = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Motivo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Profesion = new javax.swing.JTextField();
        Situacion_Economica = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        botonCancel = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        Nacionalidad = new javax.swing.JTextField();
        Localidad = new javax.swing.JTextField();
        Estado_Civil = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        NIF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Observaciones_Familiares_SB = new javax.swing.JScrollPane();
        Observaciones_Familiares = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        Experiencia_Laboral_SB = new javax.swing.JScrollPane();
        Experiencia_Laboral = new javax.swing.JTextArea();
        Observaciones_Vivienda_SB = new javax.swing.JScrollPane();
        Observaciones_Vivienda = new javax.swing.JTextArea();
        Apellidos = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Fecha_Nacimiento = new javax.swing.JFormattedTextField();
        NIF_Voluntario = new javax.swing.JTextField();
        Domicilio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        Nivel_Estudios = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Ciudad_Nacimiento = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        Codigo_Postal = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        botonOK = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        Precio_Vivienda = new javax.swing.JTextField();
        Expediente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jBotones = new javax.swing.JPanel();
        botonAniadir = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        Tipo_Vivienda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tipo_ViviendaKeyTyped(evt);
            }
        });

        jLabel15.setText("Situacion");

        jLabel6.setText("Nacimiento");

        Observaciones_Datos_Personales.setColumns(20);
        Observaciones_Datos_Personales.setRows(5);
        Observaciones_Datos_Personales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Observaciones_Datos_PersonalesKeyTyped(evt);
            }
        });
        Observaciones_Datos_Personales_SB.setViewportView(Observaciones_Datos_Personales);

        jLabel8.setText("Estado civil");

        jLabel4.setText("Nombre");

        jLabel24.setText("Motivo");

        Motivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MotivoKeyTyped(evt);
            }
        });

        jLabel23.setText("Profesión");

        Profesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ProfesionKeyTyped(evt);
            }
        });

        Situacion_Economica.setColumns(30);
        Situacion_Economica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Situacion_EconomicaKeyTyped(evt);
            }
        });

        jLabel25.setText("Observaciones de la vivienda");

        botonCancel.setText("Cancelar");
        botonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelActionPerformed(evt);
            }
        });

        Nacionalidad.setColumns(20);
        Nacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NacionalidadKeyTyped(evt);
            }
        });

        Localidad.setColumns(20);
        Localidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LocalidadKeyTyped(evt);
            }
        });

        Estado_Civil.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Estado_Civil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Casado", "Divorciado", "Soltero", "Viudo" }));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Beneficiarios");

        NIF.setColumns(9);
        NIF.setEditable(false);
        NIF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NIFKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Modificar a un beneficiario");

        jLabel28.setText("Tipo");

        jLabel29.setText("Observaciones de los familiares");

        Observaciones_Familiares.setColumns(20);
        Observaciones_Familiares.setRows(5);
        Observaciones_Familiares.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Observaciones_FamiliaresKeyTyped(evt);
            }
        });
        Observaciones_Familiares_SB.setViewportView(Observaciones_Familiares);

        jLabel7.setText("Nacionalidad");

        jLabel9.setText("Domicilio");

        jLabel27.setText("Experiencia laboral");

        Experiencia_Laboral.setColumns(20);
        Experiencia_Laboral.setRows(5);
        Experiencia_Laboral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Experiencia_LaboralKeyTyped(evt);
            }
        });
        Experiencia_Laboral_SB.setViewportView(Experiencia_Laboral);

        Observaciones_Vivienda_SB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Observaciones_Vivienda_SBKeyTyped(evt);
            }
        });

        Observaciones_Vivienda.setColumns(20);
        Observaciones_Vivienda.setRows(5);
        Observaciones_Vivienda_SB.setViewportView(Observaciones_Vivienda);

        Apellidos.setColumns(30);
        Apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApellidosKeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setText("Familiares");

        jLabel20.setText("NIF Voluntario");

        Fecha_Nacimiento.setColumns(9);
        Fecha_Nacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        Fecha_Nacimiento.setText("d/mm/aa");

        NIF_Voluntario.setBackground(new java.awt.Color(255, 255, 153));
        NIF_Voluntario.setColumns(9);
        NIF_Voluntario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NIF_VoluntarioKeyTyped(evt);
            }
        });

        Domicilio.setColumns(30);
        Domicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DomicilioKeyTyped(evt);
            }
        });

        jLabel10.setText("Codigo Postal");

        Nivel_Estudios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nivel_EstudiosKeyTyped(evt);
            }
        });

        jLabel22.setText("Estudios");

        jLabel21.setText("Observaciones de los datos personales");

        Ciudad_Nacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ciudad_NacimientoKeyTyped(evt);
            }
        });

        jLabel19.setText("en");

        jLabel40.setText("Expediente");

        Codigo_Postal.setColumns(9);
        Codigo_Postal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Codigo_PostalKeyTyped(evt);
            }
        });

        Telefono.setColumns(9);
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });

        jLabel16.setText("Email");

        Email.setColumns(20);
        Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailKeyTyped(evt);
            }
        });

        jLabel5.setText("Apellidos");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Vivienda");

        Nombre.setColumns(20);
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });

        jLabel18.setText("Precio Vivienda");

        botonOK.setText("Ok");
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });

        jLabel12.setText("Telefono");

        jLabel2.setText("NIF");

        jLabel11.setText("Localidad");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Situación economica");

        Expediente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ExpedienteKeyTyped(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diaketas/Iconos/beneficiarios.png"))); // NOI18N

        jBotones.setEnabled(false);
        jBotones.setLayout(new java.awt.GridLayout());

        botonAniadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diaketas/Iconos/aniadir_familiar.png"))); // NOI18N
        botonAniadir.setText("Añadir");
        botonAniadir.setEnabled(false);
        botonAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirActionPerformed(evt);
            }
        });
        jBotones.add(botonAniadir);

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diaketas/Iconos/eliminar_familiar.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.setEnabled(false);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jBotones.add(botonEliminar);

        botonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diaketas/Iconos/modificar_familiar.png"))); // NOI18N
        botonModificar.setText("Modificar");
        botonModificar.setEnabled(false);
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });
        jBotones.add(botonModificar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(25, 25, 25))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(NIF, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Expediente, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Fecha_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Ciudad_Nacimiento))
                                    .addComponent(Estado_Civil, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Nivel_Estudios)
                                            .addComponent(Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(Codigo_Postal))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Localidad, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                            .addComponent(jLabel16)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Profesion, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                                    .addComponent(Domicilio)
                                    .addComponent(Motivo)
                                    .addComponent(Apellidos)))
                            .addComponent(jLabel21)
                            .addComponent(jLabel3)
                            .addComponent(jLabel27)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Experiencia_Laboral_SB)
                            .addComponent(Observaciones_Datos_Personales_SB))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator6)
                                .addComponent(jBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel28))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Precio_Vivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Tipo_Vivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(Observaciones_Vivienda_SB, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Situacion_Economica))
                                .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Observaciones_Familiares_SB, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12))))
            .addGroup(layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(botonOK, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NIF_Voluntario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancel))
                .addGap(81, 494, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40)
                            .addComponent(jLabel2)
                            .addComponent(Expediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(Motivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(Tipo_Vivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Precio_Vivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Fecha_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(Ciudad_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Estado_Civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Codigo_Postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(Localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Nivel_Estudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23)
                                .addComponent(Profesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Experiencia_Laboral_SB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Observaciones_Datos_Personales_SB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Observaciones_Vivienda_SB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(Situacion_Economica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Observaciones_Familiares_SB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIF_Voluntario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonOK)
                    .addComponent(botonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelActionPerformed
        UI.cl.show(UI.jPrincipal, "Beneficiarios");
    }//GEN-LAST:event_botonCancelActionPerformed

    private void NacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NacionalidadKeyTyped
        if (Nacionalidad.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_NacionalidadKeyTyped

    private void LocalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LocalidadKeyTyped
        if (Localidad.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_LocalidadKeyTyped

    private void NIFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NIFKeyTyped
        if (NIF.getText().length() == 9) {
            evt.consume();
        }
    }//GEN-LAST:event_NIFKeyTyped

    private void ApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidosKeyTyped
        if (Apellidos.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_ApellidosKeyTyped

    private void NIF_VoluntarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NIF_VoluntarioKeyTyped
        if (NIF_Voluntario.getText().length() == 9) {
            evt.consume();
        }
    }//GEN-LAST:event_NIF_VoluntarioKeyTyped

    private void DomicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DomicilioKeyTyped
        if (Domicilio.getText().length() == 50) {
            evt.consume();
        }
    }//GEN-LAST:event_DomicilioKeyTyped

    private void EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyTyped
        if (Email.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_EmailKeyTyped

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        if (Nombre.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_NombreKeyTyped

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed
        //Fase de edición
        if (fase == 0){
            if (NIF.getText().compareTo("") == 0)
                JOptionPane.showMessageDialog(this, "El NIF del beneficiario no se ha introducido.", "NIF Beneficiario", JOptionPane.ERROR_MESSAGE);
            else if (Nombre.getText().compareTo("") == 0)
                JOptionPane.showMessageDialog(this, "El nombre del beneficiario no se ha introducido.", "Nombre Beneficiario", JOptionPane.ERROR_MESSAGE);
            else if (NIF_Voluntario.getText().compareTo("") == 0)
                JOptionPane.showMessageDialog(this, "El NIF del voluntario no se ha introducido.", "NIF Voluntario", JOptionPane.ERROR_MESSAGE);
            else if (Email.getText().compareTo("") != 0 && !ValidarCampos.isEmail(Email.getText()))
                JOptionPane.showMessageDialog(this, "El Email del beneficiario no es correcto.", "Email Beneficiario", JOptionPane.ERROR_MESSAGE);
            else if (Codigo_Postal.getText().compareTo("") != 0 && !ValidarCampos.isInteger(Codigo_Postal.getText()))
                JOptionPane.showMessageDialog(this, "El codigo postal no es correcto. Debe ser un numero", "Codigo postal Beneficiario", JOptionPane.ERROR_MESSAGE);
            else if (Expediente.getText().compareTo("") != 0 && !ValidarCampos.isInteger(Expediente.getText()))
                JOptionPane.showMessageDialog(this, "El expediente del beneficiario no es correcto.", "Expediente Beneficiario", JOptionPane.ERROR_MESSAGE);
            else if (Telefono.getText().compareTo("") != 0 && !ValidarCampos.isInteger(Telefono.getText()))
                JOptionPane.showMessageDialog(this, "El telefono no es correcto. Debe ser de tipo numerico", "Telefono Beneficiario", JOptionPane.ERROR_MESSAGE);
            else if (Precio_Vivienda.getText().compareTo("") != 0 && !ValidarCampos.isDouble(Precio_Vivienda.getText()))
                JOptionPane.showMessageDialog(this, "El precio de la vivienda no es correcto. Debe ser un numero", "Precio de la vivienda Beneficiario", JOptionPane.ERROR_MESSAGE);
            else{

                /*---------Introducir datos del familiar---------------*/

                /*Conversion de la fecha*/
                Date Fecha_Nac = null;
                SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yy");
                try {
                    Fecha_Nac = formatoFecha.parse(Fecha_Nacimiento.getText());

                    /*IntroducirDatosBeneficiario*/
                    boolean correcto = diaketas.diaketas.ong.gestorBeneficiarios.introducirDatosBeneficiario(
                            NIF.getText().toUpperCase(),
                            Nombre.getText(),
                            Apellidos.getText(),
                            Fecha_Nac,
                            Localidad.getText(),
                            datosBeneficiario.Activo,
                            datosBeneficiario.FechaDesac,
                            Email.getText(),
                            (Telefono.getText().compareTo("")==0? 0 : Integer.parseInt(Telefono.getText())),
                            Nacionalidad.getText(),
                            (String)Estado_Civil.getSelectedItem(),
                            Domicilio.getText(),
                            (Codigo_Postal.getText().compareTo("")==0? 0 : Integer.parseInt(Codigo_Postal.getText())),
                            new Date(),
                            (Expediente.getText().compareTo("")==0? 0 : Integer.parseInt(Expediente.getText())),
                            Motivo.getText(),
                            (Precio_Vivienda.getText().compareTo("")==0? 0.0 : Double.parseDouble(Precio_Vivienda.getText())),
                            Tipo_Vivienda.getText(),
                            Observaciones_Datos_Personales.getText(),
                            Observaciones_Familiares.getText(),
                            Observaciones_Vivienda.getText(),
                            Ciudad_Nacimiento.getText(),
                            Situacion_Economica.getText(),
                            Nivel_Estudios.getText(),
                            Profesion.getText(),
                            Experiencia_Laboral.getText(),
                            NIF_Voluntario.getText());

                    /*finalizar() */
                    if (correcto == true){
                        /*confirmarModificacionBeneficiario*/
                        ONG.gestorBeneficiarios.confirmarModificacionBeneficiario();

                        /*Actualizamos la pantalla principal*/           
                        //panel = new jFamiliar();
                        //UI.jPrincipal.add("Familiar", panel);
                        //UI.cl.show(UI.jPrincipal, "Familiar");       
                        botonAniadir.setEnabled(true);
                        botonEliminar.setEnabled(true);
                        botonModificar.setEnabled(true);
                        deshabilitarEdicion();
                        fase = 1;
                    }else{
                        JOptionPane.showMessageDialog(this, "No se ha encontrado ningún voluntario con ese NIF.",
                                "NIF Voluntario", JOptionPane.ERROR_MESSAGE);               
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(jAltaBeneficiario.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Fecha de nacimiento incorrecto, utilice formato dd/MM/yy.", "Fecha de Nacimiento", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            UI.cl.show(UI.jPrincipal, "Beneficiarios");
        }

    }//GEN-LAST:event_botonOKActionPerformed

    public void deshabilitarEdicion(){
        NIF.setEditable(false);
        Nombre.setEditable(false);
        Apellidos.setEditable(false);
        Fecha_Nacimiento.setEditable(false);
        Localidad.setEditable(false);
        Email.setEditable(false);
        Telefono.setEditable(false);
        Nacionalidad.setEditable(false);
        Estado_Civil.setEditable(false);
        Domicilio.setEditable(false);
        Codigo_Postal.setEditable(false);
        Expediente.setEditable(false);
        Motivo.setEditable(false);
        Precio_Vivienda.setEditable(false);
        Tipo_Vivienda.setEditable(false);
        Observaciones_Datos_Personales.setEditable(false);
        Observaciones_Familiares.setEditable(false);
        Observaciones_Vivienda.setEditable(false);
        Ciudad_Nacimiento.setEditable(false);
        Situacion_Economica.setEditable(false);
        Nivel_Estudios.setEditable(false);
        Profesion.setEditable(false);
        Experiencia_Laboral.setEditable(false);
        NIF_Voluntario.setEditable(false);
    }
    private void MotivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MotivoKeyTyped
        if (Motivo.getText().length() == 50) {
            evt.consume();
        }
    }//GEN-LAST:event_MotivoKeyTyped

    private void Ciudad_NacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ciudad_NacimientoKeyTyped
        if (Ciudad_Nacimiento.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_Ciudad_NacimientoKeyTyped

    private void Nivel_EstudiosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nivel_EstudiosKeyTyped
        if (Nivel_Estudios.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_Nivel_EstudiosKeyTyped

    private void ProfesionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProfesionKeyTyped
        if (Profesion.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_ProfesionKeyTyped

    private void Experiencia_LaboralKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Experiencia_LaboralKeyTyped
        if (Experiencia_Laboral.getText().length() == 500) {
            evt.consume();
        }
    }//GEN-LAST:event_Experiencia_LaboralKeyTyped

    private void Observaciones_Datos_PersonalesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Observaciones_Datos_PersonalesKeyTyped
        if (Observaciones_Datos_Personales.getText().length() == 100) {
            evt.consume();
        }
    }//GEN-LAST:event_Observaciones_Datos_PersonalesKeyTyped

    private void Tipo_ViviendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tipo_ViviendaKeyTyped
        if (Tipo_Vivienda.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_Tipo_ViviendaKeyTyped

    private void Observaciones_Vivienda_SBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Observaciones_Vivienda_SBKeyTyped
        if (Nombre.getText().length() == 100) {
            evt.consume();
        }
    }//GEN-LAST:event_Observaciones_Vivienda_SBKeyTyped

    private void Situacion_EconomicaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Situacion_EconomicaKeyTyped
        if (Situacion_Economica.getText().length() == 50) {
            evt.consume();
        }
    }//GEN-LAST:event_Situacion_EconomicaKeyTyped

    private void Observaciones_FamiliaresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Observaciones_FamiliaresKeyTyped
        if (Observaciones_Familiares.getText().length() == 100) {
            evt.consume();
        } 
    }//GEN-LAST:event_Observaciones_FamiliaresKeyTyped

    private void Codigo_PostalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Codigo_PostalKeyTyped
        if (Codigo_Postal.getText().length() == 5) {
            evt.consume();
        } 
    }//GEN-LAST:event_Codigo_PostalKeyTyped

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        if (Telefono.getText().length() == 9) {
            evt.consume();
        } 
    }//GEN-LAST:event_TelefonoKeyTyped

    private void ExpedienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ExpedienteKeyTyped
        if (Expediente.getText().length() == 9) {
            evt.consume();
        } 
    }//GEN-LAST:event_ExpedienteKeyTyped

    private void botonAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirActionPerformed
        panel = new jAltaFamiliar("ModificarBeneficiario");

        UI.jPrincipal.add("AltaFamiliar", panel);
        UI.cl.show(UI.jPrincipal, "AltaFamiliar");
    }//GEN-LAST:event_botonAniadirActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        panel = new jListarFamiliar("ModificarBeneficiario", "BajaFamiliar");

        UI.jPrincipal.add("ListarFamiliar", panel);
        UI.cl.show(UI.jPrincipal, "ListarFamiliar");
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        panel = new jListarFamiliar("ModificarBeneficiario", "ModificarFamiliar");

        UI.jPrincipal.add("ListarFamiliar", panel);
        UI.cl.show(UI.jPrincipal, "ListarFamiliar");
    }//GEN-LAST:event_botonModificarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellidos;
    private javax.swing.JTextField Ciudad_Nacimiento;
    private javax.swing.JTextField Codigo_Postal;
    private javax.swing.JTextField Domicilio;
    private javax.swing.JTextField Email;
    private javax.swing.JComboBox Estado_Civil;
    private javax.swing.JTextField Expediente;
    private javax.swing.JTextArea Experiencia_Laboral;
    private javax.swing.JScrollPane Experiencia_Laboral_SB;
    private javax.swing.JFormattedTextField Fecha_Nacimiento;
    private javax.swing.JTextField Localidad;
    private javax.swing.JTextField Motivo;
    private javax.swing.JTextField NIF;
    private javax.swing.JTextField NIF_Voluntario;
    private javax.swing.JTextField Nacionalidad;
    private javax.swing.JTextField Nivel_Estudios;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextArea Observaciones_Datos_Personales;
    private javax.swing.JScrollPane Observaciones_Datos_Personales_SB;
    private javax.swing.JTextArea Observaciones_Familiares;
    private javax.swing.JScrollPane Observaciones_Familiares_SB;
    private javax.swing.JTextArea Observaciones_Vivienda;
    private javax.swing.JScrollPane Observaciones_Vivienda_SB;
    private javax.swing.JTextField Precio_Vivienda;
    private javax.swing.JTextField Profesion;
    private javax.swing.JTextField Situacion_Economica;
    private javax.swing.JTextField Telefono;
    private javax.swing.JTextField Tipo_Vivienda;
    private javax.swing.JButton botonAniadir;
    private javax.swing.JButton botonCancel;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonOK;
    private javax.swing.JPanel jBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
