/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diaketas.UI;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author kesada
 */
public class UI extends javax.swing.JFrame {
     
    /**
     * Creates new form Main
     */
    public UI() {
        initComponents();
        Container contentPane = getContentPane();
        
        /*Paneles acciones */
        JPanel crear_usuario = new crearUsuario();
        JPanel dar_baja_usuario = new darBajaUsuario();
        /*Paneles menus*/
        JPanel menu_otro = new menuOtro();
        JPanel menu_usuario = new menuUsuario();
        
        /*JPrincipal*/
        jPrincipal.add("Crear Usuario", crear_usuario);
        jPrincipal.add("Dar baja Usuario", dar_baja_usuario);
        
        /*JMenu*/
        jMenuLateral.add("Menu Usuario", menu_usuario);
        jMenuLateral.add("Menu Otro", menu_otro);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuLateral = new javax.swing.JPanel();
        jMenuBotones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 400));
        setPreferredSize(new java.awt.Dimension(550, 400));

        jMenuLateral.setBackground(new java.awt.Color(102, 0, 102));
        jMenuLateral.setPreferredSize(new java.awt.Dimension(100, 275));
        jMenuLateral.setLayout(new java.awt.CardLayout());
        getContentPane().add(jMenuLateral, java.awt.BorderLayout.WEST);

        jMenuBotones.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Beneficiario");
        jButton1.setPreferredSize(new java.awt.Dimension(118, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jMenuBotones.add(jButton1);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jMenuBotones.add(jButton2);

        jButton3.setText("jButton3");
        jMenuBotones.add(jButton3);

        getContentPane().add(jMenuBotones, java.awt.BorderLayout.NORTH);

        jPrincipal.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*Modificamos zona principal*/
        CardLayout cl = (CardLayout)(jPrincipal.getLayout());
        cl.show(jPrincipal, "Crear Usuario");
        /*Modificamos menu*/
        cl = (CardLayout)(jMenuLateral.getLayout());
        cl.show(jMenuLateral, "Menu Usuario");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*Modificamos zona principal*/
        CardLayout cl = (CardLayout)(jPrincipal.getLayout());
        cl.show(jPrincipal, "Dar baja Usuario");
        /*Modificamos menu*/
        cl = (CardLayout)(jMenuLateral.getLayout());
        cl.show(jMenuLateral, "Menu Otro");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jMenuBotones;
    private javax.swing.JPanel jMenuLateral;
    private javax.swing.JPanel jPrincipal;
    // End of variables declaration//GEN-END:variables
}
